### ISSUE TITLE
Apt cache is not updated after adding the sources

### ISSUE THREAD

**Issue by johannesE** [spitfast/ansible-elixir-role#1]
The `cache_valid_time=3600` is necessary to avoid wasting time, but fails if we have another task doing something similar that runs earlier in the playbook.
Maybe we could integrate a flag, like this?

```
  - name: Check if elixir is installed
    command: dpkg-query -W elixir
    register: elixir_check_deb
    failed_when: elixir_check_deb.rc > 1
    changed_when: elixir_check_deb.rc == 1

  - name: download erlang and elixir packages
    get_url:
      url="https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
      dest="/tmp/erlang-solutions_1.0_all.deb"
    when: elixir_check_deb.rc == 1

  - name: add erlang packages to the dpkg
    shell: "dpkg -i erlang-solutions_1.0_all.deb"
    when: elixir_check_deb.rc == 1

  - name: ensure apt cache is up to date
    apt:
      update_cache: yes
    when: elixir_check_deb.rc == 1

...
```
